# -*- coding: utf-8 -*
en_url = [
        # 一级类目频道页
        "https://www.joybuy.com/category/875061538-phones-accessories.html",
        ' https://www.joybuy.com/category/875071892-home-appliances.html',
        "https://www.joybuy.com/category/875062507-Consumer-Electronics.html",
        "https://www.joybuy.com/category/875061446-computer-office.html",
        "https://www.joybuy.com/category/875071955-wigs-hair-extensions.html",
        "https://www.joybuy.com/category/875061819-women-clothing.html",
        "https://www.joybuy.com/category/875061442-men-clothing.html",
        "https://www.joybuy.com/category/87505-sports-outdoors.html",
        "https://www.joybuy.com/category/87502-home-garden.html",
        "https://www.joybuy.com/category/87503-health-beauty.html",
        "https://www.joybuy.com/category/875062575-shoes-bags.html",
        "https://www.joybuy.com/category/875062454-jewelry-watches.html",
        "https://www.joybuy.com/category/87506-automotive-accessories.html",
        "https://www.joybuy.com/category/875071892-home-appliances.html",
        "https://www.joybuy.com/category/875062819-toys-kids-baby.html",
        'https://www.joybuy.com/600256740.html',
        'https://sale.joybuy.com/pc/Bbs6QhqwtZ.html',
        'https://www.joybuy.com/',
        'https://help.joybuy.com/help/question-list.html',
        'https://cart.joybuy.com/cart/cart.html',
        'https://trade.joybuy.com/order/confirm.html',
        'https://imsg.joybuy.com/usercenter/news/importantList.html',
        'https://www.joybuy.com/sale/pc/2cnm6iuUEMop.html',
        'https://mall.joybuy.com/pc/index-3747.html',
        'https://www.joybuy.com/651509891.html',
        'https://www.joybuy.com/search?keywords=Camera&arriveCountry=2456&filterTypes=expand&bucket=6',
        'https://www.joybuy.com/map/sitemap.html',
        'https://www.joybuy.com/discount/sitemap-a.html',
        'https://www.joybuy.com/channel/digital.html',
        'https://www.joybuy.com/superdeals/detail.html',

        ]
es_url = [
        'https://www.joybuy.es/',
        'https://sale.joybuy.es/pc/Bbs6QhqwtZ.html',
        'https://help.joybuy.es/help/question-list.html',
        'https://cart.joybuy.es/cart/cart.html',
        'https://trade.joybuy.es/order/confirm.html',
        'https://imsg.joybuy.es/usercenter/news/importantList.html',
        'https://www.joybuy.es/sale/pc/2cnm6iuUEMop.html',
        'https://mall.joybuy.es/pc/index-3747.html',
        'https://www.joybuy.es/651509891.html',
        'https://www.joybuy.es/search?keywords=Camera&arriveCountry=2456&filterTypes=expand&bucket=6',
        "//www.joybuy.es/category/875061538-phones-accessories.html",
        'https://www.joybuy.es/category/875071892-home-appliances.html',
        "//www.joybuy.es/category/875062507-Consumer-Electronics.html",
        "//www.joybuy.es/category/875061446-esputer-office.html",
        "//www.joybuy.es/category/875071955-wigs-hair-extensions.html",
        "//www.joybuy.es/category/875061819-women-clothing.html",
        "//www.joybuy.es/category/875061442-men-clothing.html",
        "//www.joybuy.es/category/87505-sports-outdoors.html",
        "//www.joybuy.es/category/87502-home-garden.html",
        "//www.joybuy.es/category/87503-health-beauty.html",
        "//www.joybuy.es/category/875062819-toys-kids-baby.html",
        "//www.joybuy.es/category/875062575-shoes-bags.html",
        "//www.joybuy.es/category/875062454-jewelry-watches.html",
        "//www.joybuy.es/category/87506-automotive-accessories.html",
        "//www.joybuy.es/category/875071892-home-appliances.html",
        'https://www.joybuy.es/map/sitemap.html',
        'https://www.joybuy.es/discount/sitemap-a.html',
        'https://www.joybuy.es/channel/digital.html',
        'https://www.joybuy.es/superdeals/detail.html',
    ]
ru_url = [
        "https://www.jd.ru/category/875064285-phones-accessories.html",
        'https://www.jd.ru/category/875065256-consumer-electronics.html',
        "https://www.jd.ru/category/875064192-computer-office.html",
        "https://www.jd.ru/category/875072078-home-appliances.html",
        "https://www.jd.ru/category/875064188-men-clothing-accessories.html",
        "https://www.jd.ru/category/875064568-women-clothing-accessories.html",
        "https://www.jd.ru/category/875063307-sports-outdoors.html",
        "https://www.jd.ru/category/875063304-home-garden.html",
        "https://www.jd.ru/category/875063305-health-beauty.html",
        "https://www.jd.ru/category/875065568-toys-kids-baby.html",
        "https://www.jd.ru/category/875065324-shoes-bags.html",
        "https://www.jd.ru/category/875065203-jewelry-watches.html",
        "https://www.jd.ru/category/875063308-automotive-accessories.html",
        "https://www.jd.ru/category/875072014-wigs-hair-extensions.html",
        'https://www.jd.ru/',
        'https://sale.jd.ru/pc/Bbs6QhqwtZ.html',
        'https://help.jd.ru/help/question-list.html',
        'https://cart.jd.ru/cart/cart.html',
        'https://trade.jd.ru/order/confirm.html',
        'https://imsg.jd.ru/usercenter/news/importantList.html',
        'https://www.jd.ru/sale/pc/2cnm6iuUEMop.html',
        'https://mall.jd.ru/pc/index-3747.html',
        'https://www.jd.ru/651509891.html',
        'https://www.jd.ru/search?keywords=Camera&arriveCountry=2456&filterTypes=expand&bucket=6',

        'https://www.jd.ru/map/sitemap.html',
        'https://www.jd.ru/discount/sitemap-a.html',
        'https://www.jd.ru/channel/digital.html',
        'https://www.jd.ru/superdeals/detail.html',
    ]
doc_adr = 'd:\1roman\autotest\head1\text'

a=['1','2','3','4','4']
print(a)
b="".join(a)
print(b)
print("d:"+b[1:])